apiVersion: carto.run/v1alpha1
kind: ClusterTemplate
metadata:
  name: mock-block-unregister
spec:
  lifecycle: tekton
  template:
    apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(workload.metadata.name)$-block-unregister-
    spec:
      params:
      - name: provider_id
        value: $(workload.spec.params[0].value)$
      - name: account_id
        value: $(workload.spec.params[2].value)$
      - name: tenant_id
        value: $(workload.spec.params[3].value)$
      - name: block_num
        value: "$(workload.spec.params[4].value)$"
      - name: task_name
        value: $(workload.spec.params[13].value)$
      - name: xterm_user
        value: $(workload.spec.params[8].value)$
      - name: iam_group_list
        value: $(workload.spec.params[9].value)$
      - name: fake
        value: $(sources.mock-cluster-unregister.url)$ # This value force the waitting, even when is not used.
      pipelineRef:
        name: $(workload.spec.params[13].value)$
      taskRunTemplate:
        serviceAccountName: $(workload.spec.params[11].value)$
      workspaces:
      - name: $(workload.spec.params[12].value)$
        persistentVolumeClaim:
          claimName: x-$(workload.spec.params[12].value)$
