apiVersion: carto.run/v1alpha1
kind: ClusterSupplyChain
metadata:
  name: mock-clusters-register-unregister
spec:
  selector:
    workload-type: cluster-register-unregister
  resources:
  #---------------------------------------------------------------------
  # Cluster register and unregister
  #---------------------------------------------------------------------
    - name: cluster-register
      templateRef:
        kind: ClusterSourceTemplate
        name: mock-cluster-register
    - name: cluster-unregister
      templateRef:
        kind: ClusterSourceTemplate
        name: mock-cluster-unregister
      sources:
        - resource: cluster-register
          name: mock-cluster-register
    - name: block-unregister
      templateRef:
        kind: ClusterTemplate
        name: mock-block-unregister
      sources:
        - resource: cluster-unregister
          name: mock-cluster-unregister
  #---------------------------------------------------------------------
  # ServiceId register and unregister
  #---------------------------------------------------------------------

