apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: mock-serviceid-register
spec:
  urlPath: status.pipelineSpec.tasks[0].params[0].value
  revisionPath: status.pipelineSpec.tasks[0].params[1].value
  lifecycle: tekton
  template:
    apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(workload.metadata.name)$-register-
    spec:
      params:
      - name: operation
        value: $(workload.spec.params[0].value)$
      - name: service_id_type
        value: $(workload.spec.params[1].value)$
      - name: account_id
        value: $(workload.spec.params[2].value)$
      - name: tenant_id
        value: $(workload.spec.params[3].value)$
      - name: provider_id
        value: $(workload.spec.params[4].value)$
      - name: provider_account_id
        value: "$(workload.spec.params[5].value)$"
      - name: additional_config
        value: "$(workload.spec.params[6].value)$"
      pipelineRef:
        name: "$(workload.spec.params[8].value)$"
      taskRunTemplate:
        serviceAccountName: "$(workload.spec.params[7].value)$"
