apiVersion: carto.run/v1alpha1
kind: ClusterSourceTemplate
metadata:
  name: source
spec:
  
  # urlPath and revisionPath, are fixed values that the ClusterSourceTemplate
  # output. This must be populated with something in order to be consumed by the next
  # step in the supplyChain, even if the next step does not do anything with it.
  
  # urlPath: status.conditions[?(@.reason=="Succeeded")].status
  # revisionPath: status.conditions[?(@.reason=="Succeeded")].status
  urlPath: status.pipelineSpec.tasks[9].params[8].value
  revisionPath: status.pipelineSpec.tasks[9].params[1].value
  lifecycle: tekton
  template:
    apiVersion: tekton.dev/v1
    kind: PipelineRun
    metadata:
      generateName: $(workload.metadata.name)$-on-
    spec:
      params:
      - name: provider_id
        value: $(workload.spec.params[0].value)$
      - name: cluster_type
        value: $(workload.spec.params[1].value)$
      - name: account_id
        value: $(workload.spec.params[2].value)$
      - name: tenant_id
        value: $(workload.spec.params[3].value)$
      - name: block_num
        value: "$(workload.spec.params[4].value)$"
      - name: cluster_num
        value: "$(workload.spec.params[5].value)$"
      - name: task_name
        value: $(workload.spec.params[6].value)$
      - name: xterm_user
        value: $(workload.spec.params[8].value)$
      - name: iam_group_list
        value: $(workload.spec.params[9].value)$
      - name: delivery_group
        value: $(workload.spec.params[10].value)$
      pipelineRef:
        name: $(workload.spec.params[6].value)$
      taskRunTemplate:
        serviceAccountName: $(workload.spec.params[11].value)$
      workspaces:
      - name: $(workload.spec.params[12].value)$
        persistentVolumeClaim:
          claimName: x-$(workload.spec.params[12].value)$
